const wordData = [
  { word: "前年", meaning: "the year before last year; two years ago", example: "我前年去了日本旅行。(I traveled to Japan the year before last.)" },
  { word: "包", meaning: "bag; package", example: "這個包很輕。(This bag is very light.)" },
  { word: "當地", meaning: "local", example: "我想買一些當地的食物。(I want to buy some local food.)" },
  { word: "名產", meaning: "local specialty; famous product", example: "這裡的名產是茶葉。(The local specialty here is tea.)" },
  { word: "明信片", meaning: "postcard", example: "我寄了一張明信片給朋友。(I sent a postcard to my friend.)" },
  { word: "訂", meaning: "to reserve; to book", example: "我訂了一間旅館。(I booked a hotel.)" },
  { word: "免費", meaning: "free (of charge)", example: "這家咖啡廳提供免費茶水。(This café offers free tea.)" },
  { word: "無線網路", meaning: "Wi-Fi", example: "這裡有免費無線網路。(There is free Wi-Fi here.)" },
  { word: "美麗", meaning: "beautiful", example: "山上的風景很美麗。(The scenery on the mountain is beautiful.)" },
  { word: "美", meaning: "beautiful", example: "這朵花真美。(This flower is really pretty.)" },
  { word: "毛", meaning: "dime; ten cents", example: "這個蘋果三毛錢。(This apple costs thirty cents.)" },
  { word: "讓", meaning: "to let; to allow; to permit", example: "這張照片讓我很感動。(This photo makes me feel touched.)" },
  { word: "正在", meaning: "progressive marker; while doing something", example: "我正在看書。(I am reading a book.)" },
  { word: "公路", meaning: "highway", example: "這條公路很筆直。(This highway is very straight.)" },
  { word: "石頭", meaning: "stone; rock", example: "河邊有很多石頭。(There are many stones by the river.)" },
  { word: "掉", meaning: "to drop; to fall", example: "手機掉在地上了。(The phone fell on the ground.)" },
  { word: "下來", meaning: "down", example: "貓從樹上跳下來。(The cat jumped down from the tree.)" },
  { word: "一下子／一下子兒", meaning: "a while; in a short moment", example: "雨一下子下大了。(It suddenly started raining hard.)" },
  { word: "光", meaning: "nothing left; running out", example: "餅乾都吃光了。(All the cookies were eaten up.)" },
  { word: "鐵路", meaning: "railway", example: "這條鐵路通往南部。(This railway leads to the south.)" },
  { word: "鐵", meaning: "iron", example: "這把椅子是鐵做的。(This chair is made of iron.)" },
  { word: "網頁", meaning: "web page", example: "你可以在網頁上查資料。(You can look up information on the webpage.)" },
  { word: "訂位", meaning: "to make a reservation; to book", example: "我們需要先訂位。(We need to reserve seats first.)" },
  { word: "底", meaning: "in the end of; bottom", example: "箱子底有一張紙。(There is a piece of paper at the bottom of the box.)" },
  { word: "出發", meaning: "to depart; to set out", example: "我們明天早上七點出發。(We will depart at 7 a.m. tomorrow.)" },
  { word: "國家公園", meaning: "national park (M: 座)", example: "這個國家公園很受歡迎。(This national park is very popular.)" },
  { word: "爬", meaning: "to climb; to crawl", example: "我們打算去爬山。(We plan to go hiking.)" },
  { word: "座位", meaning: "seat", example: "這裡沒有空的座位了。(There are no empty seats here.)" },
  { word: "位子", meaning: "seat; place (informal)", example: "你們還有位子嗎？(Do you still have seats available?)" },
  { word: "記", meaning: "to write down; to note down", example: "請記一下時間。(Please note the time.)" },
  { word: "日期", meaning: "date", example: "請確認活動的日期。(Please confirm the date of the event.)" }
];
