const wordData = [
{ word: "前年", meaning: "the year before last year; two years ago", example: "我前年去了日本旅行。(I traveled to Japan the year before last.)" },
{ word: "包", meaning: "bag; package", example: "这个包很轻。(This bag is very light.)" },
{ word: "当地", meaning: "local", example: "我想买一些当地的食物。(I want to buy some local food.)" },
{ word: "名产", meaning: "local specialty; famous product", example: "这里的名产是茶叶。(The local specialty here is tea.)" },
{ word: "明信片", meaning: "postcard", example: "我寄了一张明信片给朋友。(I sent a postcard to my friend.)" },
{ word: "订", meaning: "to reserve; to book", example: "我订了一间旅馆。(I booked a hotel.)" },
{ word: "免费", meaning: "free (of charge)", example: "这家咖啡厅提供免费茶水。(This café offers free tea.)" },
{ word: "无线网路", meaning: "Wi-Fi", example: "这里有免费无线网路。(There is free Wi-Fi here.)" },
{ word: "美丽", meaning: "beautiful", example: "山上的风景很美丽。(The scenery on the mountain is beautiful.)" },
{ word: "美", meaning: "beautiful", example: "这朵花真美。(This flower is really pretty.)" },
{ word: "毛", meaning: "dime; ten cents", example: "这个苹果三毛钱。(This apple costs thirty cents.)" },
{ word: "让", meaning: "to let; to allow; to permit", example: "这张照片让我很感动。(This photo makes me feel touched.)" },
{ word: "正在", meaning: "progressive marker; while doing something", example: "我正在看书。(I am reading a book.)" },
{ word: "公路", meaning: "highway", example: "这条公路很笔直。(This highway is very straight.)" },
{ word: "石头", meaning: "stone; rock", example: "河边有很多石头。(There are many stones by the river.)" },
{ word: "掉", meaning: "to drop; to fall", example: "手机掉在地上了。(The phone fell on the ground.)" },
{ word: "下来", meaning: "down", example: "猫从树上跳下来。(The cat jumped down from the tree.)" },
{ word: "一下子／一下子儿", meaning: "a while; in a short moment", example: "雨一下子下大了。(It suddenly started raining hard.)" },
{ word: "光", meaning: "nothing left; running out", example: "饼干都吃光了。(All the cookies were eaten up.)" },
{ word: "铁路", meaning: "railway", example: "这条铁路通往南部。(This railway leads to the south.)" },
{ word: "铁", meaning: "iron", example: "这把椅子是铁做的。(This chair is made of iron.)" },
{ word: "网页", meaning: "web page", example: "你可以在网页上查资料。(You can look up information on the webpage.)" },
{ word: "订位", meaning: "to make a reservation; to book", example: "我们需要先订位。(We need to reserve seats first.)" },
{ word: "底", meaning: "in the end of; bottom", example: "箱子底有一张纸。(There is a piece of paper at the bottom of the box.)" },
{ word: "出发", meaning: "to depart; to set out", example: "我们明天早上七点出发。(We will depart at 7 a.m. tomorrow.)" },
{ word: "国家公园", meaning: "national park (M: 座)", example: "这个国家公园很受欢迎。(This national park is very popular.)" },
{ word: "爬", meaning: "to climb; to crawl", example: "我们打算去爬山。(We plan to go hiking.)" },
{ word: "座位", meaning: "seat", example: "这里没有空的座位了。(There are no empty seats here.)" },
{ word: "位子", meaning: "seat; place (informal)", example: "你们还有位子吗？(Do you still have seats available?)" },
{ word: "记", meaning: "to write down; to note down", example: "请记一下时间。(Please note the time.)" },
{ word: "日期", meaning: "date", example: "请确认活动的日期。(Please confirm the date of the event.)" }
];
